/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-04-06 16:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NuevoUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function inicializarPagina(){\r\n");
      out.write("\tdocument.getElementById(\"btnSubmit\").onclick = verificarYEnviar;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function verificarYEnviar(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar nombreUsuario = document.getElementById(\"txtNombre\").value;\r\n");
      out.write("\tif(nombreUsuario == \"\"){\r\n");
      out.write("\t\talert('Debe completar el nombre de usuario');\r\n");
      out.write("\t\treturn false; \r\n");
      out.write("\t}\r\n");
      out.write("\tif(nombreUsuario.length < 4){\r\n");
      out.write("\t\talert('El nombre de usuario debe tener al menos 4 caractéres');\r\n");
      out.write("\t\treturn false; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar password = document.getElementById(\"txtPass\").value;\r\n");
      out.write("\tif(password == \"\"){\r\n");
      out.write("\t\talert('La contraseña no puede estar vacía');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(password.length < 6){\r\n");
      out.write("\t\talert('La contraseña debe tener al menos 6 caracteres');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar re1 = /[0-9]/;\r\n");
      out.write("\tvar re2 = /[a-z]/;\r\n");
      out.write("\tvar re3 = /[A-Z]/;\r\n");
      out.write("\tif(!re1.test(password) || !re2.test(password) || !re3.test(password)) {\r\n");
      out.write("        alert('La contraseña debe tener al menos una letra mayúscula, una minúscula y un número');\r\n");
      out.write("        return false;\r\n");
      out.write("     }\r\n");
      out.write("\t \r\n");
      out.write("\tvar email = document.getElementById(\"txtMail\").value;\r\n");
      out.write("\tre1 = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/i;\r\n");
      out.write("    if(!re1.test(email)){\r\n");
      out.write("\t\talert('Verique la dirección de mail');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    return true;\r\n");
      out.write("\t//document.getElementById(\"mainForm\").submit();\r\n");
      out.write("\t//document.getElementById(\"enviar\").onclick();\r\n");
      out.write("}\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Nuevo Usuario</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"inicializarPagina();\">\r\n");
      out.write("\t<form id=\"mainForm\" name=\"mainForm\" method=\"POST\" action=\"NuevoUsuario\" enctype=\"application/x-www-form-urlencoded\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Usuario:</td> <td><input type=\"text\" maxlength=\"25\" id=\"txtNombre\" /> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Contraseña:</td> <td><input type=\"password\" maxlength=\"25\" id=\"txtPass\" /> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Mail:</td> <td><input type=\"text\" maxlength=\"60\" id=\"txtMail\" /> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> </td> <td align=\"right\"> <input type=\"submit\" id=\"btnSubmit\" value=\"Crear\" onclick=\"return verificarYEnviar();\"/> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
